// Package certgen creates the self-signed CA, server certificate, and client
// certificates sd-report-collector uses for mTLS, writing them below a
// per-installation directory (normally /etc/sd-report-collector).
package certgen

import (
	"crypto/rand"
	"crypto/rsa"
	"crypto/x509"
	"crypto/x509/pkix"
	"encoding/pem"
	"fmt"
	"math/big"
	"net"
	"os"
	"path/filepath"
	"strings"
	"time"
)

// DefaultBaseDir is where generated certificates are stored.
const DefaultBaseDir = "/etc/sd-report-collector"

const (
	caCertFile     = "ca.pem"
	caKeyFile      = "ca.key"
	serverCertFile = "server.pem"
	serverKeyFile  = "server.key"
	clientsSubdir  = "clients"

	confDropinSubdir = "sd-report-collector.conf.d"
	confDropinFile   = "certgen.conf"

	rsaKeyBits   = 2048
	caValidity   = 10 * 365 * 24 * time.Hour
	certValidity = 2 * 365 * 24 * time.Hour

	certFileMode = 0o644
	keyFileMode  = 0o600
	dirMode      = 0o755
)

const confDropinTemplate = `# Generated by 'sd-report-certs init'. Rerun with --force to regenerate;
# manual edits here will be overwritten.
[Server]
ServerCertificateFile=%s
ServerKeyFile=%s
ClientCAFile=%s
`

// Init (re)generates the CA and the server certificate/key under baseDir.
// It refuses to overwrite an existing CA or server certificate unless force
// is set, since regenerating the CA invalidates every certificate signed by
// the previous one.
func Init(baseDir string, force bool) error {
	if err := os.MkdirAll(baseDir, dirMode); err != nil {
		return fmt.Errorf("creating %s: %w", baseDir, err)
	}
	if err := os.MkdirAll(filepath.Join(baseDir, clientsSubdir), dirMode); err != nil {
		return fmt.Errorf("creating clients directory: %w", err)
	}

	caCertPath := filepath.Join(baseDir, caCertFile)
	caKeyPath := filepath.Join(baseDir, caKeyFile)
	serverCertPath := filepath.Join(baseDir, serverCertFile)
	serverKeyPath := filepath.Join(baseDir, serverKeyFile)
	dropinPath := filepath.Join(baseDir, confDropinSubdir, confDropinFile)

	if !force {
		if existing := firstExisting(caCertPath, caKeyPath, serverCertPath, serverKeyPath, dropinPath); existing != "" {
			return fmt.Errorf("%s already exists (use --force to regenerate; this invalidates all existing client certificates)", existing)
		}
	}

	caKey, err := generateKey()
	if err != nil {
		return fmt.Errorf("generating CA key: %w", err)
	}

	serial, err := newSerialNumber()
	if err != nil {
		return err
	}
	now := time.Now()
	caTemplate := &x509.Certificate{
		SerialNumber:          serial,
		Subject:               pkix.Name{CommonName: "sd-report-collector CA"},
		NotBefore:             now,
		NotAfter:              now.Add(caValidity),
		KeyUsage:              x509.KeyUsageCertSign | x509.KeyUsageCRLSign | x509.KeyUsageDigitalSignature,
		BasicConstraintsValid: true,
		IsCA:                  true,
	}
	caCertDER, err := x509.CreateCertificate(rand.Reader, caTemplate, caTemplate, &caKey.PublicKey, caKey)
	if err != nil {
		return fmt.Errorf("creating CA certificate: %w", err)
	}
	caCert, err := x509.ParseCertificate(caCertDER)
	if err != nil {
		return fmt.Errorf("parsing generated CA certificate: %w", err)
	}

	if err := writeCert(caCertPath, caCertDER, force); err != nil {
		return err
	}
	if err := writeKey(caKeyPath, caKey, force); err != nil {
		return err
	}

	hostname, err := os.Hostname()
	if err != nil {
		hostname = "localhost"
	}
	if err := issueCert(caCert, caKey, serverCertPath, serverKeyPath, hostname, []string{hostname, "localhost"}, x509.ExtKeyUsageServerAuth, force); err != nil {
		return err
	}

	if err := os.MkdirAll(filepath.Dir(dropinPath), dirMode); err != nil {
		return fmt.Errorf("creating %s: %w", filepath.Dir(dropinPath), err)
	}
	dropin := fmt.Sprintf(confDropinTemplate, serverCertPath, serverKeyPath, caCertPath)
	if err := writeFile(dropinPath, []byte(dropin), certFileMode, force); err != nil {
		return err
	}

	fmt.Printf("CA certificate:     %s\n", caCertPath)
	fmt.Printf("CA key:             %s\n", caKeyPath)
	fmt.Printf("Server certificate: %s\n", serverCertPath)
	fmt.Printf("Server key:         %s\n", serverKeyPath)
	fmt.Printf("Config drop-in:     %s\n", dropinPath)
	return nil
}

// Client generates a certificate/key for the given client name, signed by
// the CA created by Init, and stores it under baseDir/clients. name becomes
// both the certificate's CommonName and its only DNS SAN, matching how the
// server derives the report-storage hostname from client certificates.
func Client(baseDir, name string, force bool) error {
	if err := validateName(name); err != nil {
		return err
	}

	caCert, caKey, err := loadCA(baseDir)
	if err != nil {
		return err
	}

	clientDir := filepath.Join(baseDir, clientsSubdir)
	if err := os.MkdirAll(clientDir, dirMode); err != nil {
		return fmt.Errorf("creating clients directory: %w", err)
	}

	certPath := filepath.Join(clientDir, name+".pem")
	keyPath := filepath.Join(clientDir, name+".key")
	if !force {
		if existing := firstExisting(certPath, keyPath); existing != "" {
			return fmt.Errorf("%s already exists (use --force to overwrite)", existing)
		}
	}

	if err := issueCert(caCert, caKey, certPath, keyPath, name, []string{name}, x509.ExtKeyUsageClientAuth, force); err != nil {
		return err
	}

	fmt.Printf("Client certificate: %s\n", certPath)
	fmt.Printf("Client key:         %s\n", keyPath)
	return nil
}

func issueCert(caCert *x509.Certificate, caKey *rsa.PrivateKey, certPath, keyPath, commonName string, dnsNames []string, extKeyUsage x509.ExtKeyUsage, force bool) error {
	key, err := generateKey()
	if err != nil {
		return fmt.Errorf("generating key for %s: %w", commonName, err)
	}

	serial, err := newSerialNumber()
	if err != nil {
		return err
	}
	now := time.Now()
	template := &x509.Certificate{
		SerialNumber: serial,
		Subject:      pkix.Name{CommonName: commonName},
		DNSNames:     dnsNames,
		NotBefore:    now,
		NotAfter:     now.Add(certValidity),
		KeyUsage:     x509.KeyUsageDigitalSignature | x509.KeyUsageKeyEncipherment,
		ExtKeyUsage:  []x509.ExtKeyUsage{extKeyUsage},
	}
	if ip := net.ParseIP(commonName); ip != nil {
		template.IPAddresses = []net.IP{ip}
	}

	certDER, err := x509.CreateCertificate(rand.Reader, template, caCert, &key.PublicKey, caKey)
	if err != nil {
		return fmt.Errorf("creating certificate for %s: %w", commonName, err)
	}

	if err := writeCert(certPath, certDER, force); err != nil {
		return err
	}
	return writeKey(keyPath, key, force)
}

func loadCA(baseDir string) (*x509.Certificate, *rsa.PrivateKey, error) {
	caCertPath := filepath.Join(baseDir, caCertFile)
	caKeyPath := filepath.Join(baseDir, caKeyFile)

	certPEM, err := os.ReadFile(caCertPath)
	if err != nil {
		return nil, nil, fmt.Errorf("reading CA certificate (run 'init' first): %w", err)
	}
	keyPEM, err := os.ReadFile(caKeyPath)
	if err != nil {
		return nil, nil, fmt.Errorf("reading CA key (run 'init' first): %w", err)
	}

	certBlock, _ := pem.Decode(certPEM)
	if certBlock == nil {
		return nil, nil, fmt.Errorf("%s: no PEM data found", caCertPath)
	}
	caCert, err := x509.ParseCertificate(certBlock.Bytes)
	if err != nil {
		return nil, nil, fmt.Errorf("parsing %s: %w", caCertPath, err)
	}

	keyBlock, _ := pem.Decode(keyPEM)
	if keyBlock == nil {
		return nil, nil, fmt.Errorf("%s: no PEM data found", caKeyPath)
	}
	caKey, err := x509.ParsePKCS1PrivateKey(keyBlock.Bytes)
	if err != nil {
		return nil, nil, fmt.Errorf("parsing %s: %w", caKeyPath, err)
	}

	return caCert, caKey, nil
}

func generateKey() (*rsa.PrivateKey, error) {
	return rsa.GenerateKey(rand.Reader, rsaKeyBits)
}

func newSerialNumber() (*big.Int, error) {
	limit := new(big.Int).Lsh(big.NewInt(1), 128)
	serial, err := rand.Int(rand.Reader, limit)
	if err != nil {
		return nil, fmt.Errorf("generating certificate serial number: %w", err)
	}
	return serial, nil
}

func writeCert(path string, der []byte, force bool) error {
	data := pem.EncodeToMemory(&pem.Block{Type: "CERTIFICATE", Bytes: der})
	return writeFile(path, data, certFileMode, force)
}

func writeKey(path string, key *rsa.PrivateKey, force bool) error {
	data := pem.EncodeToMemory(&pem.Block{Type: "RSA PRIVATE KEY", Bytes: x509.MarshalPKCS1PrivateKey(key)})
	return writeFile(path, data, keyFileMode, force)
}

func writeFile(path string, data []byte, perm os.FileMode, force bool) error {
	flags := os.O_WRONLY | os.O_CREATE | os.O_TRUNC
	if !force {
		flags |= os.O_EXCL
	}
	f, err := os.OpenFile(path, flags, perm)
	if err != nil {
		if os.IsExist(err) {
			return fmt.Errorf("%s already exists (use --force to overwrite)", path)
		}
		return fmt.Errorf("writing %s: %w", path, err)
	}
	defer f.Close()

	if err := f.Chmod(perm); err != nil {
		return fmt.Errorf("setting permissions on %s: %w", path, err)
	}
	if _, err := f.Write(data); err != nil {
		return fmt.Errorf("writing %s: %w", path, err)
	}
	return nil
}

func firstExisting(paths ...string) string {
	for _, p := range paths {
		if _, err := os.Stat(p); err == nil {
			return p
		}
	}
	return ""
}

func validateName(name string) error {
	if name == "" {
		return fmt.Errorf("client name must not be empty")
	}
	if name == "." || name == ".." || strings.ContainsAny(name, "/\\") {
		return fmt.Errorf("invalid client name %q", name)
	}
	return nil
}
